<div class="row">
    <div class="col-md-12">
        <h1>Machines</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Actions</th>
                    <th>Plant Name</th>
                    <th>Site</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->machines as $machine): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('titanium/default', array('controller' => 'machine', 'action' => 'edit', 'id' => $machine->getId()));?>"><i class="fa fa-edit"></i></a>
                        <a href="<?php echo $this->url('titanium/default', array('controller' => 'machine', 'action' => 'delete', 'id' => $machine->getId())); ?>"><i class="fa fa-remove"></i></a>
                    </td>
                    <td><?php echo $this->escapeHtml($machine->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($machine->getType()); ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>