<?php
    $this->headScript()->appendFile('/js/datatables.js')
                       ->appendFile('/js/bootstrap/tab.js')
                       ->appendFile('/js/jquery-plugin/stickytabs.js')
                       ->appendFile('/js/titanium/plant/detail.js');
?>

<div class="row">
    <div class="col-md-12 title">
            
        <h1>Plant Details</h1>
        <hr>
            
        <i class="fa fa-building fa-3x pull-left"></i>
        <h4><?php echo $this->plant->getName(); ?></h4>
        <p>
            <a href="<?php echo $this->url('titanium/default', array('controller' => 'plant', 'action' => 'edit', 'id' => $this->plant->getId())); ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('titanium/default', array('controller' => 'plant', 'action' => 'delete', 'id' => $this->plant->getId())); ?>"><i class="fa fa-remove"></i></a>
        </p>
        
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="tabs">
            <li role="presentation" class="active"><a href="#details" aria-controls="home"    role="tab" data-toggle="tab">Details</a></li>
            <li role="presentation"><a href="#history"                aria-controls="history" role="tab" data-toggle="tab">History</a></li>
        </ul>
        
        <!-- Tab panes -->
        <div class="tab-content">
            
            <!-- Details tab -->
            <div role="tabpanel" class="tab-pane active" id="details">
                <div class="row">
                    <div class="col-lg-6">
                        <table class="table table-condensed table-bordered">
                            <tbody>
                                <tr>
                                    <th style="width: 35%;">Name</th>
                                    <td><?php echo $this->plant->getName(); ?></td>
                                </tr>
                                <tr>
                                    <th>Type</th>
                                    <td><?php echo $this->plant->getSite(); ?></td>
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- History tab -->
            <div role="tabpanel" class="tab-pane" id="history">
                No history to show yet.
            </div>
            
        </div>
        
    </div>
</div>