<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Titanium'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Style sheets -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,700')
                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
                        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
                        ->appendStylesheet('/css/titanium.css')
                        ->appendStylesheet('/css/app.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
                                      ->prependFile($this->basePath('/js/jquery-1.11.3.min.js'))
                                     
                                      ->appendFile($this->basePath('js/jquery.ssd-vertical-navigation.js'));
        ?>

    </head>
    <body>
        
        <div class="l-header l-row">
            <img class="logo" src="/img/titanium-logo.png">
            <span class="title">Titanium Application</span>
            <span class="identity"><?php echo $this->profileLink();?></span>
        </div>
        
        <div class="l-body l-row">
            
            <!-- Side navigation -->
            <div class="l-nav l-col l-scroll-y">
               <?php echo $this->navigation('navigation')->menu()
                                                          ->setMinDepth(0)
                                                          ->setMaxDepth(0)
                                                          ->setUlClass('side-nav')
                                                          ->escapeLabels(false);
                ?> 
            </div>
        
            <!-- content -->
            <div class="l-content l-col">
                
                <div class="l-row">
                    <div class="breadcrumb">
                        
                    </div>
                </div>
                <div class="l-row l-pane l-scroll-y">
                    <div class="container-fluid">
                        <?php echo $this->content; ?>
                    </div>
                </div>
                
            </div>
        </div>
       
        <!-- footer -->
        <div class="l-footer l-row">
            <span class="pull-right">by S Rayner</span>
        </div>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
