<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Titanium Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Style sheets -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,600" rel="stylesheet" type="text/css">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='/css/app.css' rel="stylesheet" type="text/css">
        

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->appendFile($this->basePath('js/app.js'))
            ->appendFile($this->basePath('js/jquery.ssd-vertical-navigation.js'))
        ; ?>

    </head>
    <body>
        <div id="contentWrapper">
            <div id="contentLeft">
            <ul id="leftNavigation">
                <li class="active">
                    <a href="#"><i class="fa fa-gears leftNavIcon"></i> Manufacturing</a>
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Plants</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Machines</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Production</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-pencil-square-o leftNavIcon"></i> Design</a>
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> NC Programs</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Variants</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-wrench leftNavIcon"></i> System</a>
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Users</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Roles</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Access Rules</a>
                        </li>
                    </ul>
                </li>
                
            </ul>
        </div>
        
        <div id="contentRight">
            <?php echo $this->content; ?>
       </div>
       
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
